#set ur workflow
name: Node Github CI/CD 
#check the git event we need to run the job, it tells the gitaction where/wen to be build the work flow it can be single or array of event
on:
   push:
      branches:
         - develop
# specify the OS you want to run your workflow on
jobs:
  test:
       
       
  